spring.application.name=backend
spring.datasoure.url=jdbc:mysql://localhost:3306/spadb
spring.datasoure.username=root
spring.datasoure.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080